### ISSUE TITLE
Add sample data

### ISSUE THREAD

**Issue by edwardoughton** [edwardoughton/pysim5g#4]

**Comment by vaibhav-jain** [comment]
Hi @edwardoughton 

Could you please share/add this file 'data/../results/percentile_50_capacity_lut.csv'

**Comment by edwardoughton** [comment]
Hi Vaibhav, this should be created by the repo, so I'm just wondering why you want this provided as a file? In my opinion, the simulation model in the India5G repo is a more updated and better version to use to create these lookup tables. Best wishes, Ed

**Comment by vaibhav-jain** [comment]
thanks @edwardoughton  for the prompt reply 

I thought the same that it should be created by the repo, attaching the complete traceback

```
(pysim) ➜  pysim5g git:(master) ✗ python vis/vis.py
vis/vis.py:78: UserWarning: 
The palette list has fewer values (6) than needed (10) and will cycle, which may produce an uninterpretable plot.
  plot = sns.relplot(x="Inter-Site Distance (km)", y='Value', hue="Frequency (GHz)",
completed (frequency) barplot (isd)
Traceback (most recent call last):
  File "vis/vis.py", line 444, in <module>
    wide_data = load_summary_lut(max_isd_distance)
  File "vis/vis.py", line 114, in load_summary_lut
    output = pd.read_csv(filename)
  File "/usr/local/anaconda3/envs/pysim/lib/python3.8/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/anaconda3/envs/pysim/lib/python3.8/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/anaconda3/envs/pysim/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/anaconda3/envs/pysim/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 605, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/usr/local/anaconda3/envs/pysim/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1442, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/usr/local/anaconda3/envs/pysim/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1735, in _make_engine
    self.handles = get_handle(
  File "/usr/local/anaconda3/envs/pysim/lib/python3.8/site-packages/pandas/io/common.py", line 856, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/../results/percentile_50_capacity_lut.csv'



```

**Comment by edwardoughton** [comment]
Vaibhav,

Either the file hasn't been created yet because you haven't run the script to generate this lookup table, or the file path is incorrect. 

Ed

**Comment by alex-cse** [comment]
hello, 
also have the same problem here,
after running the "run.py" I do see some CSV files in the folder "result", but I can not find the file "percentile_50_capacity_lut"

**Comment by rusly1994** [comment]
+1

**Comment by ednotari** [comment]
I have the same problem. Did you manage to create the "data/../results/percentile_50_capacity_lut.csv" file?
